### ISSUE TITLE
Adapter Installation

### ISSUE THREAD

**Issue by Matzeb15** [gokturk413/ioBroker.my-opcua#20]
Hello

Do you have any documentation or can you explain how to install your adapter?
I could install the adapter and also make my setting i.e. endpoint and user credentials.
But when i start the adapter, iobroker show errors.

Following you see some log entries. Edge-js is installed but i think there is something going wrong with the installation.

`2024-01-02 15:39:29.330  - [32minfo[39m: host.ioBroker "system.adapter.my-opcua.0" enabled
2024-01-02 15:39:29.419  - [32minfo[39m: host.ioBroker instance system.adapter.my-opcua.0 started with pid 171637
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]: /opt/iobroker/node_modules/edge-js/lib/edge.js:34
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     throw new Error('The edge native module is not available at ' + builtEdge 
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     ^
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]: Error: The edge native module is not available at /opt/iobroker/node_modules/edge-js/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/agracio/edge-js
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/edge-js/lib/edge.js:34:11)
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-01-02 15:39:29.640  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-01-02 15:39:29.641  - [31merror[39m: host.ioBroker Caught by controller[0]:     at require (node:internal/modules/helpers:177:18)
2024-01-02 15:39:29.641  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.my-opcua/main.js:18:14)
2024-01-02 15:39:29.641  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-01-02 15:39:29.641  - [31merror[39m: host.ioBroker Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-02 15:39:29.641  - [31merror[39m: host.ioBroker Caught by controller[0]: Node.js v18.19.0
2024-01-02 15:39:29.641  - [31merror[39m: host.ioBroker instance system.adapter.my-opcua.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-01-02 15:39:29.641  - [32minfo[39m: host.ioBroker Restart adapter system.adapter.my-opcua.0 because enabled`

I try to connect to a siemens S7-1513 and the internal opc-server. With UAexpert the connection is working.

IoBroker is installed on Debian 12
js-controller is version 5.0.17
node-js version is v18.19.0

Thank you for your adapter and for your help

**Comment by mcm1957** [comment]
**Please note that this adapter is currently not listed at iobroker repositories.**

Installation from github is NOT recommended (by ioBroker core team) unless explicitly instructed by dev i.e. to test some special case. Github installations should never be applied to production systems.

Addition to repositories has been request some time ago As review revealed some required adaptions the pR has been closed. Until now no new PR has been received - but would be welcome to trigger e ne review very much.

https://github.com/ioBroker/ioBroker.repositories/pull/2693

Adapter currently does not pass standard ioBroker github tests too:
https://github.com/gokturk413/ioBroker.my-opcua/actions/runs/6611406090/job/17955212058

**Comment by gokturk413** [comment]
I was it developed for my purpose. It works Kepware and openindustryOpcUa servers.Do you test it in the windows.Have you instal l .net framework 4.6 , Node.js v18.14.0

**Comment by gokturk413** [comment]
It tested windows10, windows server2019
